name: CapRover Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Git branch to deploy
        required: true
        type: choice
        options: [development, production]
      server:
        description: Server to deploy to
        required: true
        type: choice
        options: [frginbox, storage]
      use_default_app_name:
        description: Use the repository name as the CapRover app name
        required: false
        type: boolean
        default: true
      custom_app_name:
        description: Custom CapRover app name (if not using the repository name)
        required: false
        type: string

jobs:
  deploy:
    uses: ultra-mega-apps/workflows-public/.github/workflows/caprover-deployment.yaml@main
    with:
      branch: ${{ inputs.branch }}
      server: ${{ inputs.server }}
      use_default_app_name: ${{ inputs.use_default_app_name }}
      custom_app_name: ${{ inputs.custom_app_name }}
    secrets: inherit
